spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab2_java
    username: postgres
    password: 1029384756
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
