package com.project2.models;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.util.List;

/**
 * Represents an owner of one or more cats in the system.
 * This class is mapped to the "owners" table in the database.
 */
@Entity
@Table(name = "owners")
public class Owners {
    /**
     * The unique identifier for the owner.
     * It is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the owner.
     */
    private String name;

    /**
     * The birthdate of the owner.
     */
    private LocalDate birthDate;

    /**
     * A list of cats owned by this owner.
     * This establishes a one-to-many relationship with the {@link Cats} entity.
     */
    @OneToMany(mappedBy = "owner")
    private List<Cats> cats;

    /**
     * Gets the unique identifier of the owner.
     *
     * @return The owner's ID.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the owner.
     *
     * @param id The new ID for the owner.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the name of the owner.
     *
     * @return The owner's name.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the owner.
     *
     * @param name The new name for the owner.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the birthdate of the owner.
     *
     * @return The owner's birthdate.
     */
    public LocalDate getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the birthdate of the owner.
     *
     * @param birthDate The new birthdate for the owner.
     */
    public void setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * Gets the list of cats owned by this owner.
     *
     * @return A list of {@link Cats} owned by this owner.
     */
    public List<Cats> getCats() {
        return cats;
    }

    /**
     * Sets the list of cats owned by this owner.
     *
     * @param cats The new list of cats for this owner.
     */
    public void setPets(List<Cats> cats) {
        this.cats = cats;
    }
}